development:
  adapter: postgresql
  encoding: unicode
  database: question_project_development
  username: postgres
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: question_project_test
  username: postgres
  pool: 5

  production:
  adapter: postgresql
  database: question_project_production
  username: postgres
  pool: 5
  timeout: 5000